Authentication with firebase
Bootcampers-GLB-Mex/ai-warmup-interview pull request #6
Opened 2024-04-10 02:20 UTC by fava2020

<img width="934" alt="Screenshot 2024-04-09 at 8 15 53 p m" src="https://github.com/Bootcampers-GLB-Mex/ai-warmup-interview/assets/62807391/5471cfc3-c645-4c98-bfd3-f4146d02c4bd">
<img width="925" alt="Screenshot 2024-04-09 at 8 15 44 p m" src="https://github.com/Bootcampers-GLB-Mex/ai-warmup-interview/assets/62807391/d5e21d2b-7e10-48b1-9d4a-5e0d268f0d00">

2024-04-10 13:53 UTC, miguelromerogutierrez requested changes

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/.env
This file must be hided by .gitignore

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +      <div className="bg-teal-100 p-10 rounded-lg shadow-xl w-96">
Can we set the tab-spacing for 2 spaces, please?

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +      <div className="bg-teal-100 p-10 rounded-lg shadow-xl w-96">
Look at this https://gist.github.com/karpolan/2c573b5767bc9b65db9936c7fad4daac

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +                            <Button handlerEvent={() => {}} title={loading ? "Logging in ..." : " Login "}></Button>
Why an empty `handlerEvent`?

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +                            <div>
Maybe is a good idea to isolate this building block into a UIField component:
```
export function UIField({label, placeholder, id, name, ....}) {
  return               <div>
                                <label htmlFor="email-address" className="sr-only">
                                    Email address
                                </label>
                                <Field
                                    type="email"
                                    id="email"
                                    name="email"
                                    value={values.email}
                                    onChange={handleChange}
                                    className="w-full p-3 bg-white rounded outline-none text-teal-900 placeholder-teal-700"
                                    placeholder="Email address"
                                />

                                <p className='text-xs text-red-600'>
                                    {errors.email && touched.email && errors.email}
                                </p>
                            </div>
}
```

then you can use it simply:

```
<>
  <UIField name="email" label="Email" .../>
  <UIField name="password" label="Password" ... />
</>
```

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +    const validateForm = (values) => {
move out this function. Maybe in a utils.ts file along this component

2024-04-10 13:53 UTC, miguelromerogutierrez commented on app-quizz/src/app/authentication/sign-up/page.jsx
> +    <div className="min-h-screen flex items-center justify-center bg-white">
here is missing consistency, use Formik and the fields, also validate the fields same as sign-in page

2024-04-10 16:03 UTC, fava2020 commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +                            <Button handlerEvent={() => {}} title={loading ? "Logging in ..." : " Login "}></Button>
My mistake 😂

2024-04-10 16:36 UTC, fava2020 commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +      <div className="bg-teal-100 p-10 rounded-lg shadow-xl w-96">
I will take a look

2024-04-10 16:50 UTC, fava2020 commented on app-quizz/src/app/authentication/sign-in/page.jsx
> +                            <div>
Nice

2024-04-10 16:51 UTC, fava2020 commented on app-quizz/src/app/authentication/sign-up/page.jsx
> +    <div className="min-h-screen flex items-center justify-center bg-white">
I will add here it

2024-04-10 19:40 UTC, fava2020 commented on app-quizz/.env
@miguelromerogutierrez I am unsure why these files are not being ignored.

2024-04-11 17:01 UTC, miguelromerogutierrez approved these changes

2024-04-11 17:01 UTC, miguelromerogutierrez commented
Looks really good

2024-04-11 17:01 UTC, merged